### ISSUE TITLE
Make independent container for KB2

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/docker-neo4j-knowledgebase#9]

**Comment by matentzn** [comment]
After trying this for four hours, we decided to go another way: using a simple docker-compose runable script (available as part of the container [here](https://github.com/VirtualFlyBrain/docker-neo4j-knowledgebase/blob/neo2owl/run.sh)). We will also continue to use the live endpoint on vfb.org for testing; the above is only necessary if a change needs to be inspected immediately.

Problem: the neo4j container does not lend itself to extension (no apt-get, no python etc). Therefore deploying as single container would require much more work, and since we are going to ditch the kb1 2 kb2 code, its not worth it.
